Likeapp/urls.py
from django.urls import path

from Likeapp.views import LikeArticleView

app_name = 'likeapp'
urlpatterns = [
    path('article/likes/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

ProfileApp/urls.py
from django.urls import path

from ProfileApp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'
urlpatterns = [
    path('create/',ProfileCreateView.as_view(),name='create'),
    path('update/<int:pk>',ProfileUpdateView.as_view(),name='update'),
]

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'
urlpatterns = [
    path('login/',LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),

    path('create_user/',AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>',AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>',AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>',AccountDeleteView.as_view(), name='delete'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from articleapp.views import ArticleListView

urlpatterns = [
    path('',ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/',include('accountapp.urls')),
    path('profiles/',include('ProfileApp.urls')),
    path('articles/',include('articleapp.urls')),
    path('comments/',include('commentapp.urls')),
    path('boards/',include('boardapp.urls')),
    path('subscribe/',include('subscribeapp.urls')),
    path('likes/',include('Likeapp.urls', namespace='Likeapp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/models.py
from django.db import models

# Create your models here.
# 관리자 페이지 접근권한 수정(사용자별로 페이지 접근권한 제한)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from boardapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,null=True,related_name='article')

    # 이 게시물이 어느 게시판(project)에 해당되는지 연결고리를 만들어줌
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True,related_name='article')

    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='article/',null=True,blank=True)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

    #좋아요 기능
    like = models.IntegerField(default=0)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUserUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 초기화 이후에 username의 값을 비활성화(
        # 이 한줄이 없으면 기본 UserCreationForm 과 다를게 없음)
        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from .decorators import account_ownership_required
from .models import *

# Create your views here.
# accountapp 은 회원가입 로그인 회원탈퇴 로그아웃 비밀번호변경 기본페이지(hello_world)

from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from accountapp.forms import AccountUserUpdateForm


has_ownership = [account_ownership_required, login_required]

# CRUD 중 CreateView를 통한 회원가입구현
class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('article:list')
    template_name = 'accountapp/create.html'


# CRUD 중 R(DetailView)를 이용해 개인페이지 구현
class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list
                                                               ,**kwargs)

# CRUD 중 U(Update View) 를 이용해 비밀번호 변경 구현
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUserUpdateForm
    template_name = 'accountapp/update.html'
    success_url = reverse_lazy('home')

# CRUD 중 D(DelteView) 를 이용해 회원탈퇴 구현
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>가입</h4>
        </div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>


    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>회원탈퇴</h4>
        </div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>


    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <div style="text-align: center; max-width: 500px; margin: 2rem auto;">

      <!--포로파일이 있다면 이미지,닉네임,메시지,편집보아게-->
      {% if target_user.profile %}
        {% if target_user.profile.image %}
          <img src="{{ target_user.profile.image.url }}" alt=""
           style="height: 10rem; width: 10rem; border-radius: 20rem; margin-bottom: 2rem;
           object-fit: cover;">
        {% endif %}
      <h2 style="font-family: NanumSquareB;">
        {{ target_user.profile.nickname }}
        <!-- 프로필 편집(이미지,닉네임,메시지)-->
        {% if target_user == user %}
        <a class="material-icons"
           style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;"
           href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
          edit
        </a>
        {% endif %}
      </h2>
      <!--  대화명(메시지) 출력 -->
      <h5 style="margin-bottom:3rem;">
        {{ target_user.profile.message }}
      </h5>

      {% else %}
        {% if target_user == user %}
        <a href="{% url 'profileapp:create' %}">
          <h2 style="font-family: 'NanumSquareB'">
            Create Profile
          </h2>
        </a>
        {% else %}
        <h2>
          프로필 미설정
        </h2>
        {% endif %}
      {% endif %}

      <!-- 비밀번호 변경(update)-->
      {% if target_user == user %}
      <a class="material-icons"
         style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .1rem;"
         href="{% url 'accountapp:update' pk=target_user.pk %}">
          settings
      </a>
      <!-- 회원탈퇴(delete) -->
      <a class="material-icons"
         style="box-shadow: 0 0 4px #fcc; border-radius: 10rem; padding: .4rem;"
         href="{% url 'accountapp:delete' pk=target_user.pk %}">
          cancel
      </a>
      {% endif %}

    </div>
<hr>
    <div>
      {% include 'snippets/list_fragment.html' with article_list=object_list%}
    </div>

  </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
      <h4>Login</h4>
    </div>
    <div>
      <form action="" method="post">
        {% csrf_token %}
        <!-- bootstrap을 적용한 폼 -->
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
      </form>
    </div>
  </div>

{% endblock%}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>비밀번호 변경</h4>
        </div>
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>


    </div>

{% endblock %}