Likeapp/urls.py
from django.urls import path

from Likeapp.views import LikeArticleView

app_name = 'likeapp'
urlpatterns = [
    path('article/likes/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'
urlpatterns = [
    path('login/',LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),

    path('create_user/',AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>',AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>',AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>',AccountDeleteView.as_view(), name='delete'),
]

commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentDeleteView, CommentUpdateView

app_name = 'comment'
urlpatterns = [
    path('create/',CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>',CommentDeleteView.as_view(), name='delete'),
    path('update/<int:pk>',CommentUpdateView.as_view(), name='update'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from articleapp.views import ArticleListView

urlpatterns = [
    path('',ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/',include('accountapp.urls')),
    path('profiles/',include('ProfileApp.urls')),
    path('articles/',include('articleapp.urls')),
    path('comments/',include('commentapp.urls')),
    path('boards/',include('boardapp.urls')),
    path('subscribe/',include('subscribeapp.urls')),
    path('likes/',include('Likeapp.urls', namespace='Likeapp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commentapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from articleapp.models import Article


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.SET_NULL,
                                null=True, related_name='comment')
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,
                                null=True, related_name='comment')
    image = models.ImageField(upload_to='comments/',null=True,blank=True)
    content = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

commentapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, UpdateView

from articleapp.models import Article
from commentapp.decorators import comment_ownership_required
from commentapp.form import CommentCreationForm
from commentapp.models import Comment



class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentCreationForm
    template_name = 'commentapp/create.html'
    #
    def form_valid(self, form):
        temp_comment = form.save(commit=False)
        temp_comment.article = Article.objects.get(pk=self.request.POST['article_pk'])
        temp_comment.writer = self.request.user
        temp_comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('article:detail',kwargs={'pk':self.object.article.pk})


@method_decorator(comment_ownership_required,'get')
@method_decorator(comment_ownership_required,'post')
class CommentDeleteView(DeleteView):
    model = Comment
    context_object_name = 'target_comment'
    template_name = 'commentapp/delete.html'

    def get_success_url(self):
        return reverse('article:detail',kwargs={'pk':self.object.article.pk})

@method_decorator(comment_ownership_required,'get')
@method_decorator(comment_ownership_required,'post')
class CommentUpdateView(UpdateView):
    model = Comment
    form_class = CommentCreationForm
    context_object_name = 'target_comment'
    template_name = 'commentapp/update.html'

    def get_success_url(self):
        return reverse('article:detail',kwargs={'pk':self.object.article.pk})

commentapp/templates/commentapp/create.html
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 1rem auto">
        <form action="{% url 'comment:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}

            {% if user.is_authenticated %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="댓글달기">
            {% else %}
            <a href="{% url 'accountapp:login' %}?next={{request.path}}"
               class="btn btn-dark rounded-pill col-6 mt-3">
                로그인
            </a>
            {% endif %}
            <input type="hidden" name="article_pk" value="{{article.pk}}">
        </form>


    </div>

{% endblock %}

commentapp/templates/commentapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>댓글을 삭제하시겠습니까?</h4>
        </div>
        <form action="{% url 'comment:delete' pk=target_comment.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>


    </div>

{% endblock %}

commentapp/templates/commentapp/detail.html
<div style="border: 1px solid; text-align: left; padding: 2%; margin: 1rem 0;
border-radius: 1rem; border-color: #bbb;">
  <div>
    <strong>
      {{ comment.writer.profile.nickname }}
    </strong>
    &nbsp&nbsp&nbsp
    {{ comment.created_at }}
  </div>
  <div style="margin: 1rem 0;">
    {% if comment.image %}
     <img style="width: 100%; border-radius: 1rem; margin: 2rem 0;"
           src="{{comment.image.url}}" alt="">
    {% endif %}
    {{ comment.content }}
  </div>

  {% if comment.writer == user %}
  <div style="text-align: right">
    <a href="{% url 'comment:update' pk=comment.pk%}"\\
    class="btn btn-warning rounded-pill px-4 btn-sm">
      수정
    </a>
    <a href="{% url 'comment:delete' pk=comment.pk%}"\\
    class="btn btn-danger rounded-pill btn-sm px-4" >
      삭제
    </a>
  </div>
  {% endif %}
  </div>

commentapp/templates/commentapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="container form_class_max_600px my-5">
    <div class="text-center my-5">
            <h1>댓글 수정</h1>
    </div>
    <div>
        <form action="{% url 'comment:update' target_comment.pk%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-3 mt-3" value="수정">

        </form>


    </div>
</div>

{% endblock %}