Likeapp/urls.py
from django.urls import path

from Likeapp.views import LikeArticleView

app_name = 'likeapp'
urlpatterns = [
    path('article/likes/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'
urlpatterns = [
    path('login/',LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),

    path('create_user/',AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>',AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>',AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>',AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreationView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    ArticleListView

app_name = 'article'
urlpatterns = [
    path('list/',ArticleListView.as_view(),name='list'),
    path('create/', ArticleCreationView.as_view(),name='create'),
    path('detail/<int:pk>',ArticleDetailView.as_view(),name='detail'),
    path('update/<int:pk>',ArticleUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',ArticleDeleteView.as_view(),name='delete'),
]

boardapp/urls.py
from django.urls import path

from boardapp.views import *

app_name= 'board'
urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', ProjectDetailView.as_view(), name='detail'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from articleapp.views import ArticleListView

urlpatterns = [
    path('',ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/',include('accountapp.urls')),
    path('profiles/',include('ProfileApp.urls')),
    path('articles/',include('articleapp.urls')),
    path('comments/',include('commentapp.urls')),
    path('boards/',include('boardapp.urls')),
    path('subscribe/',include('subscribeapp.urls')),
    path('likes/',include('Likeapp.urls', namespace='Likeapp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribe'
urlpatterns = [
    path('subscribe/',SubscriptionView.as_view(),name='subscribe'),
    path('list/',SubscriptionListView.as_view(),name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}


<body style="font-family: 'NanumSquareR';">
    {% include 'header.html' %}

    <hr>

    {% for message in messages %}
    <div class="text-center">
        <div class="btn btn-{{message.tags}} rounded-pill px-5 my-2">
            {{message}}

        </div>
    </div>
    {% endfor %}

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="pragmatic_footer">
    <div class="pragmatic_footer_button">
        <a href="#">
        <span>공지사항</span>
        </a>|
        <span>제휴문의</span> |
        <span>서비스 소개</span>

    </div>
    <div style="margin-top: 1rem">
        <h6 class="pragmatic_logo">Pragmatic</h6>
    </div>

</div>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
    <title>Pragmatic</title>

    <!--  Bootstrap link  -->
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
         integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!-- 구글폰트 링크 -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@570&display=swap" rel="stylesheet">

    <!--  구글폰트(네비게이션 바)  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Single+Day&display=swap" rel="stylesheet">

    <!--Material 아이콘 (Mypage의 프로필편집,비번변경등을 아이콘화)-->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    <!--  기본 css 링크  -->
    <link rel ="stylesheet" type="text/css" href="{% static 'base.css'%}">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
<div class="pragmatic_header">
    <div class="pragmatic_logo">
        <a href="{% url 'home' %}">
            <h1>Pragmatic</h1>
        </a>
    </div>
    <div style="font-size: 1.2rem; font-family: 'Single Day', cursive;"
         class="pragmatic_header_nav_bar">
        <a href="{% url 'article:list' %}">
            <span>메인</span>
        </a>
        <a href="{% url 'board:list' %}" class="pragmatic_header_nav">
        <span>프로젝트</span>
        </a>

        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{request.path}}"
           class="pragmatic_header_nav">
            <span>로그인</span>
        </a>
        <a href="{% url 'accountapp:create' %}"
           class="pragmatic_header_nav">
            <span>회원가입</span>
        </a>
        {% else %}
        <a href="{% url 'subscribe:list' %}" class="pragmatic_header_nav">
            <span>나의구독</span>
        </a>

        <a href="{% url 'accountapp:detail' pk=user.pk %}"
           class="pragmatic_header_nav">
            <span>MyPage</span>
        </a>

        <a href="{% url 'accountapp:logout' %}"
           class="pragmatic_header_nav">
            <span>로그아웃</span>
        </a>
        {% endif %}
    </div>
</div>