Likeapp/urls.py
from django.urls import path

from Likeapp.views import LikeArticleView

app_name = 'likeapp'
urlpatterns = [
    path('article/likes/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'
urlpatterns = [
    path('login/',LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),

    path('create_user/',AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>',AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>',AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>',AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreationView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    ArticleListView

app_name = 'article'
urlpatterns = [
    path('list/',ArticleListView.as_view(),name='list'),
    path('create/', ArticleCreationView.as_view(),name='create'),
    path('detail/<int:pk>',ArticleDetailView.as_view(),name='detail'),
    path('update/<int:pk>',ArticleUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',ArticleDeleteView.as_view(),name='delete'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from articleapp.views import ArticleListView

urlpatterns = [
    path('',ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/',include('accountapp.urls')),
    path('profiles/',include('ProfileApp.urls')),
    path('articles/',include('articleapp.urls')),
    path('comments/',include('commentapp.urls')),
    path('boards/',include('boardapp.urls')),
    path('subscribe/',include('subscribeapp.urls')),
    path('likes/',include('Likeapp.urls', namespace='Likeapp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from boardapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,null=True,related_name='article')

    # 이 게시물이 어느 게시판(project)에 해당되는지 연결고리를 만들어줌
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True,related_name='article')

    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='article/',null=True,blank=True)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

    #좋아요 기능
    like = models.IntegerField(default=0)

articleapp/forms.py
from django.forms import ModelForm
from articleapp.models import Article
from django import forms

from boardapp.models import Project


class ArticleCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'editable text-left',
                                                           'style':'height: auto;'}))

    project = forms.ModelChoiceField(queryset=Project.objects.all(),required=False)
    # 우리가입력하는게 textarea
    # text-left (부스트랩에 있는 클래스)
    class Meta:
        model = Article
        fields = ['title','image','project','content']

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render

# Create your views here.

# articleapp 은 카드형레이아웃(body 부분)
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article
from commentapp.form import CommentCreationForm


@method_decorator(login_required,'get')
@method_decorator(login_required,'post')
# 게시글 만들기
class ArticleCreationView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'
    
    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('article:detail', kwargs={'pk':self.object.pk})

# 게시글 상세정보
class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'

# 게시글 수정
@method_decorator(article_ownership_required,'get')
@method_decorator(article_ownership_required,'post')
class ArticleUpdateView(UpdateView):
    model = Article
    context_object_name = 'target_article'
    form_class = ArticleCreationForm
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('article:detail', kwargs={'pk': self.object.pk})

# 게시글 삭제
@method_decorator(article_ownership_required,'get')
@method_decorator(article_ownership_required,'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    template_name = 'articleapp/delete.html'
    success_url = reverse_lazy('article:list')


class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    ordering = ('-id')
    paginate_by = 20

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-
editor.min.css" type="text/css" media="screen" charset="utf-8">

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>게시글 등록</h4>
        </div>
        <form action="{% url 'article:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="등록">
        </form>


    </div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>게시글을 삭제하시겠습니까?</h4>
        </div>
        <form action="{% url 'article:delete' pk=target_article.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>


    </div>

{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <div style="text-align: center; max-width: 700px; margin: 4rem auto;">

      <h1>
        {{ target_article.title }}
      </h1>

       <!-- 좋아요 -->
      <div style="height:2rem; margin-bottom: 1.2rem">
        <a href="{% url 'Likeapp:article_like' pk=target_article.pk %}">
          <i class="material-icons" style="color: #ff6363; vertical-align: middle; font-size: 1.2rem">
            favorite
          </i>
         </a>
        <span style= "vertical-align: middle; font-size: 1.2rem">
          {{target_article.like}}
        </span>
      </div>
        <!--좋아요 시스템 끝-->

      <div style="text-align: center; box-shadow: #d4d4d4 0px 0px 5px; border-radius: 10rem;
            display: inline-block;">
        <a href="{% url 'accountapp:detail' pk=target_article.writer.pk %}">
          {% if target_article.writer.profile.image %}
            <img src="{{ target_article.writer.profile.image.url }}" alt=""
             style="height: 2rem; width: 2rem; border-radius: 10rem; margin:.3rem -0.3rem .3rem .3rem;
             object-fit: cover;">
          {% endif %}
          <p style="text-align: center; vertical-align: middle; display: inline-block;
            font-family: 'NanumSquareB', sans-serif; font-size: 1.1rem;
             margin: 0.3rem 0.6rem 0.3rem 0.6rem;"> {{ target_article.writer.profile.nickname }}</p>
        </a>
      </div>
      <hr>

      {% if target_article.image %}
      <img style="width: 100%; border-radius: 1rem; margin: 2rem 0;"
           src="{{target_article.image.url}}" alt="">
      {% endif %}
      <div class="text-left">
        {{target_article.content | safe}}
      </div>

      {% if target_article.writer == user %}
        <a href="{% url 'article:update' pk=target_article.pk %}"
           class="btn btn-primary rounded-pill col-3 mt-3">
          수정
        </a>
        <a href="{% url 'article:delete' pk=target_article.pk %}"
        class="btn btn-danger rounded-pill col-3 mt-3">
          삭제
        </a>
        {% endif %}
      <hr>



      <!-- 댓글 부분 (commentapp/create.html)-->
      {% for comment in target_article.comment.all %}
        {% include 'commentapp/detail.html' with comment=comment %}
      {% endfor %}

      {% include 'commentapp/create.html' with article=target_article %}

    </div>

  </div>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
  .container {
    padding: 0;
    margin: 0, auto;
  }

  .container a {
    width: 45%;
    max-width: 250px;
  }

  .container div {
    display: flex;
    justify-content: center;
    align-items: center;

    border-radius: 1rem;
}
  .container img{
    width: 100%;
    border-radius: 1rem;
  }

</style>
    {% if article_list %}
    <div class="container">
        {% for article in article_list %}
        <a href="{% url 'article:detail' pk=article.pk %}">
            {% include 'snippets/card.html' with article=article %}
        </a>
        {% endfor %}
    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script>
    {% else %}
    <div class="text-center"><!--부스트랩 라이브러리 class=text-center-->
        <h1>아직 게시글이 없습니다!</h1>
    </div>
    {% endif %}

    {% include 'snippets/pagination.html' with page_obj=page_obj %}

<!--게시글작성 버튼-->
<div style="text-align: center">
    <a href="{% url 'article:create' %}"
             class="btn btn-dark rounded-pill col-3 mt-3 mb-3 px-1">
            게시글 작성
    </a>
</div>



{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-
editor.min.css" type="text/css" media="screen" charset="utf-8">

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>게시글 수정</h4>
        </div>
        <form action="{% url 'article:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>


    </div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}